import { Expanded } from "@/app/components/widget/expanded/expanded"
import { Padding } from "@/app/components/widget/padding/padding"
import { joinCss } from "@/app/lib/utils"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en" className={joinCss(geistSans.variable, geistMono.variable)}>
      <body>
        <Expanded>
          <Padding direction="immediateUnderRoot">
            <Expanded>{children}</Expanded>
          </Padding>
        </Expanded>
      </body>
    </html>
  )
}
export default RootLayout
