import { RootLayout as PageRootLayout } from "@/app/_components/page/RootLayout"
import { Background } from "@/app/_components/widget/background/background"
import { Center } from "@/app/_components/widget/center/center"
import { Expanded } from "@/app/_components/widget/expanded/expanded"
import { Padding } from "@/app/_components/widget/padding/padding"
import { joinCss } from "@/app/_lib/utils"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { ReactNode } from "react"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode
}>) => {
  return (
    <html lang="en" className={joinCss(geistSans.variable, geistMono.variable)}>
      <body>
        <Expanded>
          <Background>
            <Padding direction="immediateUnderRoot">
              <Center axis="horizontal">
                <PageRootLayout>{children}</PageRootLayout>
              </Center>
            </Padding>
          </Background>
        </Expanded>
      </body>
    </html>
  )
}
export default RootLayout
